site_name: RAP Community of Practice
# site_url: https://example.com
repo_url: https://github.com/NHSDigital/rap-community-of-practice
repo_name: RAP Community of Practice
edit_uri: edit/main/docs/
plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
  - search
  - mkdocs-jupyter:
      include_source: True
      theme: dark
  - redirects:
      redirect_maps:
        "training_resources/git/intro-to-git.md": "training_resources/git/introduction-to-git.md"
        "about.md": "site_info/about.md"
        "our_RAP_service/thin-slice-strategy.md": "implementing_RAP/thin-slice-strategy.md"
        "glossary.md": "site_info/glossary.md"
        "support.md": "implementing_RAP/support.md"
        "implementing_RAP/technical-workflow.md": "implementing_RAP/workflow/technical-workflow.md"
        "implementing_RAP/tools.md": "implementing_RAP/workflow/tools.md"
        "implementing_RAP/coding-best-practice.md": "implementing_RAP/workflow/coding-best-practice.md"
        "implementing_RAP/code-review.md": "implementing_RAP/workflow/code-review.md"
        "implementing_RAP/notebooks_versus_ide_development.md": "implementing_RAP/workflow/notebooks_versus_ide_development.md"
        "implementing_RAP/accessibility-how-to.md": "implementing_RAP/workflow/accessibility-how-to.md"
        "implementing_RAP/quality-assuring-analytical-outputs.md": "implementing_RAP/workflow/quality-assuring-analytical-outputs.md"
        "implementing_RAP/tidy-data.md": "implementing_RAP/workflow/tidy-data.md"
        "implementing_RAP/how-to-publish-your-code-in-the-open.md": "implementing_RAP/publishing_code/how-to-publish-your-code-in-the-open.md"
        "implementing_RAP/updating-your-published-code.md": "implementing_RAP/publishing_code/updating-your-published-code.md"
        "implementing_RAP/when-to-stop-coding.md": "training_resources/coding_tips/when-to-stop-coding.md"
        "useful_links.md": "implementing_RAP/useful_links.md"
  - tags:
      tags_file: tags.md
nav:
  - Home: index.md
  - What is RAP?:
      - What is RAP?: introduction_to_RAP/what_is_RAP.md
      - Why RAP is important: introduction_to_RAP/why_RAP_is_important.md
      - Levels of RAP: introduction_to_RAP/levels_of_RAP.md
      - Government policy on RAP: introduction_to_RAP/gov-policy-on-rap.md
      - What is open source?: introduction_to_RAP/what-is-open-source.md
      - The history of RAP: introduction_to_RAP/history_of_RAP.md
      - RAP in health: introduction_to_RAP/RAP_in_health.md
  - Our RAP service:
      - our_RAP_service/index.md
      - Building team capability: our_RAP_service/building_team_capability.md
      - Support models: our_RAP_service/support-models.md
      - Typical engagement flow: our_RAP_service/typical-engagement-flow.md
      - RAP pre-engagement Questionnaire: our_RAP_service/rap-pre-engagement-questionnaire.md
      - Programme level reporting: our_RAP_service/programme-level-reporting.md
      - Service design and user research: our_RAP_service/service-design-and-user-research.md
  - Implementing RAP:
      - implementing_RAP/index.md
      - Are you ready for RAP?: implementing_RAP/rap-readiness.md
      - Technical Skills for RAP:
        - Git: implementing_RAP/skills_for_rap/git_for_rap.md
        - Python: implementing_RAP/skills_for_rap/python_for_rap.md
        - R: implementing_RAP/skills_for_rap/r_for_rap.md
      - Process Mapping: implementing_RAP/process_mapping.md
      - Thin slice strategy: implementing_RAP/thin-slice-strategy.md
      - Workflow:
        - Technical workflow: implementing_RAP/workflow/technical-workflow.md
        - Tools: implementing_RAP/workflow/tools.md
        - Coding best practice: implementing_RAP/workflow/coding-best-practice.md
        - Code review: implementing_RAP/workflow/code-review.md
        - Notebooks vs IDE development: implementing_RAP/workflow/notebooks_versus_ide_development.md
        - Guidance on accessibility: implementing_RAP/workflow/accessibility-how-to.md
        - Quality assuring analytical outputs: implementing_RAP/workflow/quality-assuring-analytical-outputs.md
        - Tidy data: implementing_RAP/workflow/tidy-data.md
      - Publishing Code:
        - How to publish your code in the open: implementing_RAP/publishing_code/how-to-publish-your-code-in-the-open.md
        - Updating published code: implementing_RAP/publishing_code/updating-your-published-code.md
        - Licensing your code: implementing_RAP/publishing_code/licensing-your-code.md
      - Example Pipeline (Python): implementing_RAP/example-pipeline.md
      - Support: implementing_RAP/support.md
      - Useful Links: implementing_RAP/useful_links.md
  - Training resources:
      - training_resources/index.md
      - Git:
          - Introduction to Git: training_resources/git/introduction-to-git.md
          - Using Git collaboratively: training_resources/git/using-git-collaboratively.md
          - Making code discoverable: training_resources/git/making-code-discoverable.md
          - Git Hooks: training_resources/git/githooks.md
          - GitHub vs GitLab Terminology: training_resources/git/github_gitlab_terminology.md
          - Quick Start Guides:
              - Git: training_resources/git/quick_start_guides/git_quick_start_guide.md
              - GitHub: training_resources/git/quick_start_guides/github_quick_start_guide.md
              - GitLab: training_resources/git/quick_start_guides/gitlab_quick_start_guide.md
          - Walkthroughs:
              - Committing Work: training_resources/git/git_walkthroughs/committing_work_walkthrough.md
              - Working with Branches: training_resources/git/git_walkthroughs/working_with_branches_walkthrough.md
              - Pull and Merge Requests: training_resources/git/git_walkthroughs/pull_and_merge_requests_walkthrough.md
      - Python:
          - Intro to Python: training_resources/python/intro-to-python.md
          - Basic Python data analysis operations: training_resources/python/basic-python-data-analysis-operations.md
          - Python functions: training_resources/python/python-functions.md
          - Visualisation in Python: training_resources/python/visualisation-in-python.md
          - Handling file paths: training_resources/python/handling-file-paths.md
          - Logging and error handling in Python: training_resources/python/logging-and-error-handling.md
          - Project structure and packaging: training_resources/python/project-structure-and-packaging.md
          - Using Python f-strings to run SQL queries: training_resources/python/using-f-strings-sql-queries.md
          - Using config files: training_resources/python/config-files.md
          - Data Classes: training_resources/python/data-classes.md
          - Virtual environments:
              - Why use virtual environments?: training_resources/python/virtual-environments/why-use-virtual-environments.md
              - Venv: training_resources/python/virtual-environments/venv.md
              - Conda: training_resources/python/virtual-environments/conda.md
          - Unit testing: training_resources/python/unit-testing.md
          - Unit testing field definitions: training_resources/python/unit-testing-field-definitions.md
          - Back testing: training_resources/python/backtesting.md
      - PySpark:
          - About PySpark: training_resources/pyspark/README.md
          - Logging and error handling in PySpark: training_resources/pyspark/logging-and-error-handling.md
          - PySpark style guide: training_resources/pyspark/pyspark-style-guide.md
          - Download our PySpark tutorial: training_resources/pyspark/pyspark-tutorial.py
          - Efficient Pyspark case study: training_resources/pyspark/efficient-pyspark-case-study.ipynb
      - R:
          - External resources: training_resources/R/README.md
          - Git with RStudio: training_resources/R/git_with_RStudio.md
      - Coding Tips:
          - When to stop coding: training_resources/coding_tips/when-to-stop-coding.md
          - Refactoring golden rules: training_resources/coding_tips/refactoring-guide.md
  - Tags: tags.md
  - Site info:
      - About: site_info/about.md
      - Acknowledgements: site_info/acknowledgements.md
      - Website Release Process: site_info/rap-release-workflow.md
      - GitHub Repository Traffic Statistics: site_info/repo_traffic_information.md
      - Glossary: site_info/glossary.md
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: indigo
  font:
    text: Arial
  logo: images/logo/nhs-blue-on-white.jpg
  favicon: images/favicon/favicon.ico
  features:
    - search.share
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
  icon:
    admonition:
      <type>: material/alert
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - tables
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NHSDigital/rap-community-of-practice
      name: NHS Digital Analytical Services
  generator: false
copyright: Copyright &copy; 2023 Crown Copyright (NHS England)
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
watch:
  - overrides
