name: Create Pull Request for Release Branch
on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: github.repository == 'NHSDigital/rap-community-of-practice'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create Pull Request
        run: |
          gh pr create --fill
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
